### ISSUE TITLE
CircleCI tests emit a false positive result

### ISSUE THREAD

**Issue by cantsin** [GSA/resources.data.gov#150]
When running CircleCI tests, I noticed that tests (specifically `htmlproofer`) are running on an empty directory and thereby always succeeding.

Example run:
```
Running ["ScriptCheck", "HtmlCheck", "LinkCheck", "ImageCheck"] on ["_site"] on *.html... 
Ran on 0 files!
HTML-Proofer finished successfully.
```

To fix this, we want to persist the generated files in the CircleCI config, e.g.:

```yaml
      - run:
          name: test
          command: npm test

      - persist_to_workspace:
          root: ./
          paths:
            - _site
```

Unfortunately, for this to work the `baseurl` needs to be set to `""`. Once #148 is merged (and there is no need for a preview url prefix anymore), we can remove `baseurl` and insert the above fix to make tests work again. (Note: #148 fixes all currently broken links)
